### ISSUE TITLE
When I change the swap_model, it still results in the same face.

### ISSUE THREAD

**Issue by bloom-tomita** [TaiTair/comfyui-simswap#3]
Thank you for the wonderful post. When I change the `swap_model`, it still results in the same face.

In the function `swap_face` found here: https://github.com/TaiTair/comfyui-simswap/blob/main/scripts/simswap_swapper.py#L196, it seems like the specified model is being passed into `model`.

However, looking here: https://github.com/TaiTair/comfyui-simswap/blob/main/scripts/simswap_swapper.py#L340, `model = create_model(opt)` seems to reinitialize the model, which suggests that the model specified in the arguments is not being used.

**Comment by TaiTair** [comment]
Hi there, I definitely did not experience that. For example, the quality of the swapped face was much better using Ghost rather than Simswap.

I understand what you are saying but if you look at the two files from which TestOptions is generated you will see that the variable opt doesn't have any parameters for the specific model. So I still believe it is using what is being passed by comfyui.

Take a look at these files for more details:  
https://github.com/TaiTair/comfyui-simswap/blob/main/scripts/simswap/options/base_options.py  
https://github.com/TaiTair/comfyui-simswap/blob/main/scripts/simswap/options/test_options.py

Also if you try to use the inswapper onnx files you'll see that it doesn't work because the tensors are different. Which does suggest that it is using the model you are selecting.
